---
- name: Set facts
  set_fact:
    nodejs_filename: "node-v{{ nodejs_version }}-linux-x64.tar.gz"
    nodejs_topdir: "node-v{{ nodejs_version }}-linux-x64"

- name: Download nodejs
  get_url:
    dest: "{{ nodejs_download_dir }}/{{ nodejs_filename }}"
    url: "{{ nodejs_site_prefix }}/v{{ nodejs_version }}/{{ nodejs_filename }}"

- name: Create directory for node
  file: name="{{ nodejs_install_dir }}" state=directory owner="{{ nodejs_owner }}" group="{{ nodejs_group }}"

- name: Expand archive
  unarchive:
    src: "{{ nodejs_download_dir }}/{{ nodejs_filename }}"
    dest: "{{ nodejs_install_dir }}"
    owner: "{{ nodejs_owner }}"
    group: "{{ nodejs_group }}"

- name: Create symbolic link
  file:
    src:  "{{ nodejs_install_dir }}/{{ nodejs_topdir }}"
    dest: "{{ nodejs_install_dir }}/node"
    state: link
    owner: "{{ nodejs_owner }}"
    group: "{{ nodejs_group }}"

- name: Clean-up download
  file:
    dest: "{{ nodejs_download_dir }}/{{ nodejs_filename }}"
    state: absent
