---
- name: create /usr/nlm directory
  file: path=/usr/nlm state=directory owner=root group=root mode=0755

- name: create app admin group
  group: "name={{ appadmin_group }}"

- name: create app admin user
  user:
    name: "{{ appadmin_user }}"
    group: "{{ appadmin_group }}"
    createhome: no
    system: yes
    home: /usr/nlm/apps

- name: create /usr/nlm/apps directory
  file: path=/usr/nlm/apps state=directory owner="{{ appadmin_user }}" group="{{ appadmin_group }}" mode=0755

- name: create .bash_profile for user
  copy:
    dest: /usr/nlm/apps/.bash_profile
    src: "{{ role_path }}/files/bash_profile"
    owner: "{{ appadmin_user }}"
    group: "{{ appadmin_group }}"
    mode: 0644

- name: create .bashrc for user
  copy:
    dest: /usr/nlm/apps/.bashrc
    src: "{{ role_path }}/files/bashrc"
    owner: "{{ appadmin_user }}"
    group: "{{ appadmin_group }}"
    mode: 0644

- name: create /usr/nlm/apps/logs directory
  file: path=/usr/nlm/apps/logs state=directory owner="{{ appadmin_user }}" group="{{ appadmin_group }}" mode=0755

- name: create /usr/nlm/apps/html directory
  file: path=/usr/nlm/apps/html state=directory owner="{{ appadmin_user }}" group="{{ appadmin_group }}" mode=0755

- name: create /usr/nlm/apps/html/index.html as default file
  copy:
    dest: /usr/nlm/apps/html/index.html
    src: "{{ role_path }}/files/index.html"
    owner: "{{ appadmin_user }}"
    group: "{{ appadmin_group }}"
    mode: 0644

- include: node.yml
  when: "{{ appadmin_include_node }}"

- include: ruby.yml
  when: "{{ appadmin_include_ruby }}"

#- name: add read-only directories for Apache httpd
#  sefcontext:
#    target: '{{item}}'
#    setype: httpd_git_something_or_other
#    state: present
#  with_items:
#   - /usr/nlm/apps/httpd
#
#- name: add read-write directories for Apache httpd
#  sefcontext:
#    target: '{{item}}'
#    setype: httpd_rw_something_t
#    state: present
#  with_items:
#   - /usr/nlm/apps/logs
#   - /usr/nlm/apps/httpd/logs
