#!/bin/bash

# NOTE: see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html
CLOUDWATCH_FILE=CloudWatchMonitoringScripts-1.2.1.zip
CLOUDWATCH_URL=http://aws-cloudwatch.s3.amazonaws.com/downloads/${CLOUDWATCH_FILE}
CLOUDWATCH_MD5=${CLOUDWATCH_FILE}.md5

mkdir -p files/tmp

if [[ -f files/tmp/${CLOUDWATCH_FILE} ]]; then
    echo "File files/tmp/${CLOUDWATCH_FILE} already present" 1>&2
else
    echo "Downloading $CLOUDWATCH_URL ..." 1>&2
    curl -L -o files/tmp/${CLOUDWATCH_FILE} ${CLOUDWATCH_URL}
    md5sum --check files/tmp/${CLOUDWATCH_MD5}
fi

