#!/bin/bash

set -e

if [[ -f $HOME/.occs_packer_variables ]];then
  . $HOME/.occs_packer_variables
else
  echo ""
  echo "Varibles for Packer not set"
  echo ""
  exit 1
fi

if [[ $# -ge 1 ]]; then
  PACKER_LOG=1
  PACKER_LOG_PATH="logs/packer_debug_$(date +"%y%m%d").log"

  if [ -f $PACKER_LOG_PATH ]; then
    PACKER_LOG_PATH="logs/packer_debug_$(date +"%y%m%d%H%M").log"
  fi

  export PACKER_LOG
  export PACKER_LOG_PATH

  packer build --on-error=ask templates/$1
  exit $?
else
  echo "I need a template file!"
  exit 1
fi
