---
- name: Set ruby package for 2.2
  set_fact:
    ruby_package: "rh-ruby22"
    ruby_devel_package: "rh-ruby22-ruby-devel"
  when: ruby_version == "2.2"

- name: Set ruby package for 2.3
  set_fact:
    ruby_package: "rh-ruby23"
    ruby_devel_package: "rh-ruby23-ruby-devel"
  when: ruby_version == "2.3"

- name: Enable scl repo
  yum: name=centos-release-scl-rh state=present

- name: Install Ruby
  yum: name={{ ruby_package }} state=present update_cache=yes

- name: Install Ruby devel
  yum: name="{{ ruby_devel_package }}" state=present update_cache=yes
  when: "{{ ruby_devel }}"

- name: Install packages needed by ruby
  yum: pkg={{item}} state=present
  with_items:
    - zlib
    - libxml2
    - libxslt
    - sqlite

# TODO: make these depend on some var, with when
- name: Install development packages
  yum: pkg={{item}} state=present
  when: "{{ ruby_devel }}"
  with_items:
    - zlib-devel
    - libxml2-devel
    - libxslt-devel
    - sqlite-devel

- name: Install /usr/nlm/apps/.gemrc
  copy:
    dest: /usr/nlm/apps/.gemrc
    src: "{{ role_path }}/files/gemrc"
    owner: platform
    group: platform
    mode: 0644

- name: Enable ruby for platform user
  lineinfile:
    # NOTE: this should be `path` in ansible >= 2.3
    dest: /usr/nlm/apps/.bashrc
    regexp: "{{ ruby_package }}"
    line: test -f /opt/rh/{{ ruby_package }}/enable && . /opt/rh/{{ ruby_package }}/enable
