---

- hosts: all
  gather_facts: yes

  vars:
    awslogs_region: us-east-1
    awslogs_logs:
     - file: /var/log/messages
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: 'var-log-messages'
       stream_name: '{instance_id}'

     - file: /var/log/secure
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: 'var-log-secure'
       stream_name: '{instance_id}'

     - file: /var/log/audit/audit.log
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: 'var-log-audit'
       stream_name: '{instance_id}'

     - file: /var/log/cloud-init.log
       format: "%Y-%m-%d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: 'instance-bootstrap-log'
       stream_name: '{instance_id}-cloud-init'

     - file: /var/log/cfn-init-cmd.log
       format: "%Y-%m-%d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: 'instance-bootstrap-log'
       stream_name: '{instance_id}-cfn-init-cmd'

     - file: /var/log/cfn-hup.log
       format: "%Y-%m-%d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: 'instance-bootstrap-log'
       stream_name: '{instance_id}-cfn-hup'

     - file: /var/log/cfn-wire.log
       format: "%Y-%m-%d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: 'instance-bootstrap-log'
       stream_name: '{instance_id}-cfn-wire'

  roles:
    # Other roles could depend on this role. Keep it first.
    - { role: occs-directories,               tags: directories }
    - { role: occs-cloud-init,                tags: cloud-init }
    # https://github.com/RedHatGov/ansible-role-800-53, forked and modified for CentOS
    # Keep this role second. It does *a lot* and we don't want it to overwrite our changes
    - { role: occs-800-53,                    tags: 800-53 }
    # Put all other roles after this line
    - { role: occs-aws,                       tags: aws }
    - { role: occs-awslogs,                   tags: awslogs }
    - { role: occs-chrony,                    tags: chrony }
    - { role: occs-ec2,                       tags: ec2 }
    # Commented out - we will try a different way
    # - { role: splunk-forwarder,               tags: splunkforwarder }
