---

- hosts: all
  gather_facts: yes

  vars:
    awslogs_region: us-east-1
    awslogs_logs:
     - file: /var/log/messages
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: Syslog
       stream_name: test-syslog

     - file: /var/log/secure
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: Syslog
       stream_name: test-syslog

  roles:
    # Other roles could depend on this role. Keep it first.
    - { role: ansible-directories,            tags: directories }
    - { role: ansible-cloud-init,             tags: cloud-init }
    # https://github.com/RedHatGov/ansible-role-800-53, forked and modified for CentOS
    # Keep this role second. It does *a lot* and we don't want it to overwrite our changes
    - { role: ansible-800-53,                 tags: 800-53 }
    # Put all other roles after this line
    - { role: ansible-aws,                    tags: aws }
    - { role: ansible-awslogs,                tags: awslogs }
    # Commented out - we will try a different way
    # - { role: splunk-forwarder,               tags: splunkforwarder }
