---

- hosts: all
  gather_facts: yes

  roles:
    # Other roles could depend on this role. Keep it first.
    - { role: occs-directories,               tags: directories }
    - { role: occs-cloud-init,                tags: cloud-init }
    # https://github.com/RedHatGov/ansible-role-800-53, forked and modified for CentOS
    # Keep this role second. It does *a lot* and we don't want it to overwrite our changes
    - { role: occs-800-53,                    tags: 800-53 }
    # Put all other roles after this line
    - { role: occs-aws,                       tags: aws }
    - { role: occs-awslogs,                   tags: awslogs }
    - { role: occs-chrony,                    tags: chrony }
    - { role: occs-ec2,                       tags: ec2 }
    - { role: occs-nlminit,                   tags: nlminit }
    # Commented out - we will try a different way
    # - { role: splunk-forwarder,               tags: splunkforwarder }
