---

- hosts: all
  gather_facts: yes
  #  remote_user: ansible

  vars:
    nodejs_version: "6.10.0"
    nodejs_install_dir: /usr/nlm/apps
    nodejs_owner: platform
    nodejs_group: platform
    platform_include_node: yes
    platform_node_path: /usr/nlm/apps/node/bin

  roles:
    # Other roles could depend on this role. Keep it first.
    - { role: ansible-directories,            tags: directories }
    - { role: ansible-cloud-init,             tags: cloud-init }
    # https://github.com/RedHatGov/ansible-role-800-53, forked and modified for CentOS
    # Keep this role second. It does *a lot* and we don't want it to overwrite our changes
    - { role: ansible-800-53,                 tags: 800-53 }
    - { role: ansible-aws,                    tags: aws }
    # Put all other roles after this line
    - { role: occsab-platform }
    - { role: occsab-httpd }
    - { role: occsab-node }
