---

- hosts: all
  gather_facts: yes
  #  remote_user: ansible

  vars:
    nodejs_version: "6.10.0"
    appadmin_include_node: yes
    appadmin_node_path: /usr/nlm/node/bin

    nodejs_install_dir: /usr/nlm
    nodejs_version: "7.10.1"

    awslogs_region: us-east-1
    awslogs_logs:
     - file: /var/log/httpd/access_log
       format: "%d/%b/%Y:%H:%M:%S %z"
       time_zone: "UTC"
       initial_position: "end_of_file"
       group_name: NLM-INT-httpd-access-log
       stream_name: '{hostname}-{instance-id}-access'

     - file: /var/log/httpd/error_log
       format: "%d %b %y %H:%M:%S.%f"
       time_zone: "UTC"
       initial_position: "end_of_file"
       group_name: NLM-INT-httpd-access-log
       stream_name: '{hostname}-{instance-id}-error'

     - file: /var/log/messages
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: NLM-INT-var-log-messages
       stream_name: '{hostname}-{instance-id}'

     - file: /var/log/secure
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: NLM-INT-var-log-secure
       stream_name: '{hostname}-{instance-id}'

     - file: /var/log/audit/audit.log
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: NLM-INT-var-log-audit
       stream_name: '{hostname}-{instance-id}'

     - file: /var/log/cloud-init.log
       format: "%Y-%m-%d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: NLM-INT-instance-bootstrap-log
       stream_name: '{hostname}-{instance-id}-cloud-init'

     - file: /var/log/cfn-init.log
       format: "%Y-%m-%d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: NLM-INT-instance-bootstrap-log
       stream_name: '{hostname}-{instance-id}-cfn-init'

     - file: /var/log/cfn-hup.log
       format: "%Y-%m-%d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: NLM-INT-instance-bootstrap-log
       stream_name: '{hostname}-{instance-id}-cfn-hup'

     - file: /var/log/cfn-wire.log
       format: "%Y-%m-%d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: NLM-INT-instance-bootstrap-log
       stream_name: '{hostname}-{instance-id}-cfn-wire'

  roles:
    # Other roles could depend on this role. Keep it first.
    - { role: occs-directories,            tags: directories }
    - { role: occs-cloud-init,             tags: cloud-init }
    # https://github.com/RedHatGov/ansible-role-800-53, forked and modified for CentOS
    # Keep this role second. It does *a lot* and we don't want it to overwrite our changes
    - { role: occs-800-53,                 tags: 800-53 }
    - { role: occs-aws,                    tags: aws }
    - { role: occs-awslogs,                tags: awslogs }
    # Commented out - we will try a different way
    # - { role: occs-splunk-forwarder,               tags: splunkforwarder }
    # Put all other roles after this line
    - occsab-httpd
    - occsab-node
    - occsab-appadmin
