---

- hosts: all
  gather_facts: yes
  #  remote_user: ansible

  vars:
    ruby_version: "2.2"
    appadmin_include_ruby: yes
    appadmin_ruby_path: /opt/rh/rh-ruby22/enable

    awslogs_region: us-east-1
    awslogs_logs:
     - file: /var/log/httpd/access_log
       format: "%d/%b/%Y:%H:%M:%S %z"
       time_zone: "UTC"
       initial_position: "end_of_file"
       group_name: Apache-Logs
       stream_name: access-logs

     - file: /var/log/httpd/error_log
       format: "%d %b %y %H:%M:%S.%f"
       time_zone: "UTC"
       initial_position: "end_of_file"
       group_name: Apache-Logs
       stream_name: error-logs

     - file: /var/log/messages
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: Syslog
       stream_name: test-syslog

     - file: /var/log/secure
       format: "%b %d %H:%M:%S"
       time_zone: "LOCAL"
       initial_position: "start_of_file"
       group_name: Syslog
       stream_name: test-syslog

  roles:
    # Other roles could depend on this role. Keep it first.
    - { role: ansible-directories,            tags: directories }
    - { role: ansible-cloud-init,             tags: cloud-init }
    # https://github.com/RedHatGov/ansible-role-800-53, forked and modified for CentOS
    # Keep this role second. It does *a lot* and we don't want it to overwrite our changes
    - { role: ansible-800-53,                 tags: 800-53 }
    - { role: ansible-aws,                    tags: aws }
    - { role: ansible-awslogs,                tags: awslogs }
    # Commented out - we will try a different way
    # - { role: splunk-forwarder,               tags: splunkforwarder }
    # Put all other roles after this line
    - occsab-httpd
    - occsab-passenger
    - occsab-ruby
    - occsab-appadmin
