---

- hosts: all
  gather_facts: yes
  #  remote_user: ansible

  vars:
    postfix_ses_packer_build: True

    awslogs_region: us-east-1

    ruby_version: "22"

    appadmin_include_ruby: yes
    appadmin_ruby_path: /opt/rh/rh-ruby22/enable

  roles:
    # Other roles could depend on this role. Keep it first.
    - { role: occs-directories,            tags: directories }
    - { role: occs-cloud-init,             tags: cloud-init }
    # https://github.com/RedHatGov/ansible-role-800-53, forked and modified for CentOS
    # Keep this role second. It does *a lot* and we don't want it to overwrite our changes
    - { role: occs-800-53,                 tags: 800-53 }
    - { role: occs-aws,                    tags: aws }
    - { role: occs-awslogs,                tags: awslogs }
    - { role: occs-chrony,                 tags: chrony }
    - { role: occs-ec2,                    tags: ec2 }
    - { role: occs-nlminit,                tags: nlminit }
    # Commented out - we will try a different way
    # - { role: occs-splunk-forwarder,               tags: splunkforwarder }
    # Put all other roles after this line
    - occsab-httpd
    - occsab-passenger
    - occsab-ruby
    - occsab-appadmin
