---
- name: create /usr/nlm directory
  file: path=/usr/nlm state=directory owner=root group=root mode=0755

- name: create platform group
  group: name=platform

- name: create platform user
  user: name=platform group=platform createhome=no home=/usr/nlm/apps

- name: create /usr/nlm/apps directory
  file: path=/usr/nlm/apps state=directory owner=platform group=platform mode=0755

- name: create /usr/nlm/apps/logs directory
  file: path=/usr/nlm/apps/logs state=directory owner=platform group=platform mode=0755

- name: create /usr/nlm/apps/html directory
  file: path=/usr/nlm/apps/html state=directory owner=platform group=platform mode=0755

- name: create /usr/nlm/apps/html/index.html as default file
  copy:
    dest: /usr/nlm/apps/html/index.html
    src: "{{ role_path }}/files/index.html"
    owner: platform
    group: platform
    mode: 0644
